version: '3'

services:  
  kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "10.128.41.145:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter 
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://10.128.41.145:8081'
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter 
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://10.128.41.145:8081'
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "10.128.41.145"
      CONNECT_PLUGIN_PATH: 'usr/share/java,etc/kafka-connect/jars'
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
    volumes:
      - "/var/kafka-connect/jars:/etc/kafka-connect/jars"
      - "/var/eip-legacy/incoming:/home"
      - "/var/eip-legacy/processed:/var"
      - "/var/eip-legacy/errors:/tmp"
    networks:
      - sdh_nw

  kafka-connect-ui:
    image: landoop/kafka-connect-ui:latest
    ports:
      - "8003:8000"
    environment:
      CONNECT_URL: "http://kafka-connect:8083/"
      PROXY: "true"
    depends_on:
      - kafka-connect
    networks:
      - sdh_nw

networks:
 sdh_nw:
   driver: bridge
