version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - esnet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
        - 80:80
    volumes:
      - ${PWD}/www:/usr/share/nginx/html:ro
      - ${PWD}/conf:/etc/nginx/
    #command: /bin/bash -c "nginx -g 'daemon off;'"
    ulimits:
      nproc: 65535
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
 
networks:
  esnet:      