version: '3.2'

services:  
  rabbit_mgmt:
    image: rabbitmq:3.7.8-management
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin 
    hostname: my-rabbit